name: Nightly data download

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 5 * * *'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: "code"

    - uses: actions/checkout@v2
      with:
        ref: "historical-data"
        path: "historic"

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: |
        cp -R $GITHUB_WORKSPACE/historic/ $GITHUB_WORKSPACE/code/data/
        npm ci
        npm run dev
      working-directory: code/data-downloader
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

    - run: |
        cp -R $GITHUB_WORKSPACE/code/data/ $GITHUB_WORKSPACE/historic/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Nightly data download"
      working-directory: historic

    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: historical-data
        directory: historic
